### ISSUE TITLE
Tlačítko pro ověření kódu z SMS

### ISSUE THREAD

**Issue by uiii** [tomasjurasek/location-history-fe#44]
Přidat k inputu pro zadání kódu z SMS tlačítko pro ověření jeho správnosti až poté aktivovat krok pro nahrání souboru.

**Comment by krtek** [comment]
@uiii To by ale znamenalo změnit API na straně serveru, ne?

**Comment by uiii** [comment]
@krtek mám pocit, že už pro to endpoint je `/verify`

**Comment by uiii** [comment]
jo je viz https://location-history-api.azurewebsites.net/swagger/index.html 

`userId` je to co vrati volani `https://location-history-api.azurewebsites.net/api/users/send`

**Comment by uiii** [comment]
klidně se toho ujmi, představuju si to tak, že vedle inputu pro kod z SMS se prida tlacitko pro overeni a az po uspesnem overeni kodu se aktivuje krok pro nahrani souboru

**Comment by krtek** [comment]
Já se k tomu nejdřív dneska večer :/
